image: mono

options:
  max-time: 3

pipelines:
  default:
    - step:
        script:
          - BUILD_NUMBER="${BITBUCKET_COMMIT}"
          - echo "Build default branch ${BUILD_NUMBER}"

          - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Debug" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln
  tags:
    release-*:
      - step:
          script:
            - BUILD_NUMBER="${BITBUCKET_COMMIT}"
            - echo "Build release ${BUILD_NUMBER}"
            - apt-get update && apt-get install -y zip

            - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/DefaultTools/bin/Release/
            - zip /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Release/ModularToolManager_${BITBUCKET_TAG}.zip ./DefaultTools.dll

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Release/
            - zip /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Release/ModularToolManager_${BITBUCKET_TAG}.zip ./ToolMangerInterface.dll

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/
            - zip -ur /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Release/ModularToolManager_${BITBUCKET_TAG}.zip ./Release
            - mkdir /artifacts
            - mv /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Release/ModularToolManager_${BITBUCKET_TAG}.zip /artifacts
          artifacts:
            - /artifacts/**
      - step:
          name: Production deployment to download area
          deployment: production
          script: 
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${BITBUCKET_CLONE_DIR}/artifacts/ModularToolManager_${BITBUCKET_TAG}.zip"
    rc-*:
      - step:
          script:
            - BUILD_NUMBER="${BITBUCKET_COMMIT}"
            - echo "Build release candidate ${BUILD_NUMBER}"
            - apt-get update && apt-get install -y zip

            - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Debug" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Debug/
            - zip /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/ModularToolManager_${BITBUCKET_TAG}.zip ./ToolMangerInterface.dll 

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/
            - zip -ur /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/ModularToolManager_${BITBUCKET_TAG}.zip ./Debug
            - mkdir /artifacts
            - mv /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/ModularToolManager_${BITBUCKET_TAG}.zip /artifacts
            - mv /artifacts/ ${BITBUCKET_CLONE_DIR}
            - ls -la ${BITBUCKET_CLONE_DIR}
            - ls -la ${BITBUCKET_CLONE_DIR}/artifacts/
          artifacts:
            - /artifacts/**
      - step:
          name: Production deployment to download area
          deployment: production
          script:
            - ls -la ${BITBUCKET_CLONE_DIR}
            - ls -la ${BITBUCKET_CLONE_DIR}/artifacts/
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${BITBUCKET_CLONE_DIR}/artifacts/ModularToolManager_${BITBUCKET_TAG}.zip"
  branches:
    master:
      - step:
          script:
            - BUILD_NUMBER="${BITBUCKET_COMMIT}"
            - echo "Build master branch ${BUILD_NUMBER}"
            - apt-get update && apt-get install -y zip

            - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Debug" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/DefaultTools/bin/Debug/
            - zip /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/LastUnstable_ModularToolManager.zip ./DefaultTools.dll

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Debug/
            - zip -u /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/LastUnstable_ModularToolManager.zip ./ToolMangerInterface.dll 

            - cd /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/
            - zip -ur /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/LastUnstable_ModularToolManager.zip ./Debug
            - mkdir /artifacts
            - mv /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/LastUnstable_ModularToolManager.zip /artifacts
          artifacts:
            - /artifacts/**
      - step:
          name: Test/Unstable deployment to download area
          deployment: test
          script:
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${BITBUCKET_CLONE_DIR}/artifacts/LastUnstable_ModularToolManager.zip"