image: mono

pipelines:
  default:
    - step:
        script:
          - echo "Build default branch"
          - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Debug" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln
  branches:
    master:
      - step:
          script:
            - BUILD_NUMBER=`git log --oneline | wc -l`
            - echo "Build master branch ${BUILD_NUMBER}"
            
            - apt-get update && apt-get install -y zip
            - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Debug" /p:Platform="Any CPU" ModularToolManger/ModularToolManger.sln
            
            - zip -r /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/AlphaDebug_ModularToolManager_Build_${BUILD_NUMBER}.zip /opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/
            - cp /opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Debug/ToolMangerInterface.dll /opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Debug/ToolMangerInterface_${BUILD_NUMBER}.dll
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/ModularToolManger/ToolMangerInterface/bin/Debug/ToolMangerInterface_${BUILD_NUMBER}.dll"
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/ModularToolManger/ModularToolManger/bin/Debug/AlphaDebug_ModularToolManager_Build_${BUILD_NUMBER}.zip"