//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularToolManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModularToolManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string About_Dependency {
            get {
                return ResourceManager.GetString("About_Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string About_GitHubUserManual {
            get {
                return ResourceManager.GetString("About_GitHubUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository:.
        /// </summary>
        public static string About_Repository_Colon {
            get {
                return ResourceManager.GetString("About_Repository_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version_Colon {
            get {
                return ResourceManager.GetString("About_Version_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to function.
        /// </summary>
        public static string AddFunction_FunctionPathWatermark {
            get {
                return ResourceManager.GetString("AddFunction_FunctionPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string AllPlugins_Header_Information {
            get {
                return ResourceManager.GetString("AllPlugins_Header_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter function order mode.
        /// </summary>
        public static string AllPlugins_Header_OrderModeEnter {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does enter the order mode, this allows you to sort the functions as you like based on a number value.
        /// </summary>
        public static string AllPlugins_Header_OrderModeEnter_Tooltip {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeEnter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave function order mode.
        /// </summary>
        public static string AllPlugins_Header_OrderModeLeave {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does leave the order mode, without saving it.
        /// </summary>
        public static string AllPlugins_Header_OrderModeLeave_Tooltip {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeLeave_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new function order.
        /// </summary>
        public static string AllPlugins_Header_OrderModeSave {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does leave the order mode and does save the changes.
        /// </summary>
        public static string AllPlugins_Header_OrderModeSave_Tooltip {
            get {
                return ResourceManager.GetString("AllPlugins_Header_OrderModeSave_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AllPlugins_Header_Settings {
            get {
                return ResourceManager.GetString("AllPlugins_Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Theme.
        /// </summary>
        public static string App_Blue_Theme {
            get {
                return ResourceManager.GetString("App_Blue_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Theme which mainly uses the color blue as a background.
        /// </summary>
        public static string App_Blue_Theme_Description {
            get {
                return ResourceManager.GetString("App_Blue_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string App_Dark_Theme {
            get {
                return ResourceManager.GetString("App_Dark_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme for the application.
        /// </summary>
        public static string App_Dark_Theme_Description {
            get {
                return ResourceManager.GetString("App_Dark_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Theme.
        /// </summary>
        public static string App_Green_Theme {
            get {
                return ResourceManager.GetString("App_Green_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Theme which mainly uses the color green as a background.
        /// </summary>
        public static string App_Green_Theme_Description {
            get {
                return ResourceManager.GetString("App_Green_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light mode.
        /// </summary>
        public static string App_Light_Theme {
            get {
                return ResourceManager.GetString("App_Light_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme for the application.
        /// </summary>
        public static string App_Light_Theme_Description {
            get {
                return ResourceManager.GetString("App_Light_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Theme.
        /// </summary>
        public static string App_Orange_Theme {
            get {
                return ResourceManager.GetString("App_Orange_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Theme which mainly uses the color orange as a background.
        /// </summary>
        public static string App_Orange_Theme_Description {
            get {
                return ResourceManager.GetString("App_Orange_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Theme.
        /// </summary>
        public static string App_Red_Theme {
            get {
                return ResourceManager.GetString("App_Red_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Theme which mainly uses the color red as a background.
        /// </summary>
        public static string App_Red_Theme_Description {
            get {
                return ResourceManager.GetString("App_Red_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Tool Manager.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project website.
        /// </summary>
        public static string Button_Open_Project {
            get {
                return ResourceManager.GetString("Button_Open_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Default_Delete {
            get {
                return ResourceManager.GetString("Default_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Default_Edit {
            get {
                return ResourceManager.GetString("Default_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string DefaultButton_Abort {
            get {
                return ResourceManager.GetString("DefaultButton_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DefaultButton_Ok {
            get {
                return ResourceManager.GetString("DefaultButton_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string DefaultButton_OpenFile {
            get {
                return ResourceManager.GetString("DefaultButton_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DefaultButton_Save {
            get {
                return ResourceManager.GetString("DefaultButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Dependency_License {
            get {
                return ResourceManager.GetString("Dependency_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Dependency_Project {
            get {
                return ResourceManager.GetString("Dependency_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the path saved on this function is missing, the extension is wrong or the plugin for execution was removed. Please edit the function to fix the error..
        /// </summary>
        public static string FunctionButton_Method_Error {
            get {
                return ResourceManager.GetString("FunctionButton_Method_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Order.
        /// </summary>
        public static string FunctionButton_Sort_Watermark {
            get {
                return ResourceManager.GetString("FunctionButton_Sort_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filter checking if the item does contain the search string as a whole.
        /// </summary>
        public static string FunctionButtonContainsNeedleFilter_description {
            get {
                return ResourceManager.GetString("FunctionButtonContainsNeedleFilter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Filter.
        /// </summary>
        public static string FunctionButtonContainsNeedleFilter_name {
            get {
                return ResourceManager.GetString("FunctionButtonContainsNeedleFilter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filter using fuzzy search to check if an item is valid.
        /// </summary>
        public static string FunctionButtonFuzzyFilter_description {
            get {
                return ResourceManager.GetString("FunctionButtonFuzzyFilter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzzy Filter.
        /// </summary>
        public static string FunctionButtonFuzzyFilter_name {
            get {
                return ResourceManager.GetString("FunctionButtonFuzzyFilter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for function.
        /// </summary>
        public static string FunctionSelection_SearchForFunction {
            get {
                return ResourceManager.GetString("FunctionSelection_SearchForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort the current action or close the current modal.
        /// </summary>
        public static string Hotkey_Abort_Description {
            get {
                return ResourceManager.GetString("Hotkey_Abort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Hotkey_Abort_Name {
            get {
                return ResourceManager.GetString("Hotkey_Abort_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language, Add/Edit Function, Settings.
        /// </summary>
        public static string Hotkey_Abort_WorkingOn {
            get {
                return ResourceManager.GetString("Hotkey_Abort_WorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working at the following places:.
        /// </summary>
        public static string Hotkey_Abort_WorkingOn_Prefix_Colon {
            get {
                return ResourceManager.GetString("Hotkey_Abort_WorkingOn_Prefix_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the about page of the application.
        /// </summary>
        public static string Hotkey_About_Description {
            get {
                return ResourceManager.GetString("Hotkey_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About page.
        /// </summary>
        public static string Hotkey_About_Name {
            get {
                return ResourceManager.GetString("Hotkey_About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the application into the system tray.
        /// </summary>
        public static string Hotkey_Hide_Description {
            get {
                return ResourceManager.GetString("Hotkey_Hide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Application.
        /// </summary>
        public static string Hotkey_Hide_Name {
            get {
                return ResourceManager.GetString("Hotkey_Hide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the change language dialog.
        /// </summary>
        public static string Hotkey_Language_Description {
            get {
                return ResourceManager.GetString("Hotkey_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Application language.
        /// </summary>
        public static string Hotkey_Language_Name {
            get {
                return ResourceManager.GetString("Hotkey_Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        public static string Hotkey_Main_Window_WorkinOn {
            get {
                return ResourceManager.GetString("Hotkey_Main_Window_WorkinOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new function.
        /// </summary>
        public static string Hotkey_New_Description {
            get {
                return ResourceManager.GetString("Hotkey_New_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Function.
        /// </summary>
        public static string Hotkey_New_Name {
            get {
                return ResourceManager.GetString("Hotkey_New_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug found within the application.
        /// </summary>
        public static string Hotkey_Report_Bug_Description {
            get {
                return ResourceManager.GetString("Hotkey_Report_Bug_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report bug.
        /// </summary>
        public static string Hotkey_Report_Bug_Name {
            get {
                return ResourceManager.GetString("Hotkey_Report_Bug_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctrl.
        /// </summary>
        public static string Key_Ctrl {
            get {
                return ResourceManager.GetString("Key_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string Key_Esc {
            get {
                return ResourceManager.GetString("Key_Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string Key_F1 {
            get {
                return ResourceManager.GetString("Key_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12.
        /// </summary>
        public static string Key_F12 {
            get {
                return ResourceManager.GetString("Key_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string Key_H {
            get {
                return ResourceManager.GetString("Key_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        public static string Key_L {
            get {
                return ResourceManager.GetString("Key_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string Key_N {
            get {
                return ResourceManager.GetString("Key_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Description.
        /// </summary>
        public static string NewFunction_Description {
            get {
                return ResourceManager.GetString("NewFunction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Display Name.
        /// </summary>
        public static string NewFunction_Name {
            get {
                return ResourceManager.GetString("NewFunction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Parameters.
        /// </summary>
        public static string NewFunction_Parameters {
            get {
                return ResourceManager.GetString("NewFunction_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string Plugin_Authors_Colon {
            get {
                return ResourceManager.GetString("Plugin_Authors_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Plugin_Description_Colon {
            get {
                return ResourceManager.GetString("Plugin_Description_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Plugin_DisplayName_Colon {
            get {
                return ResourceManager.GetString("Plugin_DisplayName_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Plugin_License_Colon {
            get {
                return ResourceManager.GetString("Plugin_License_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project url:.
        /// </summary>
        public static string Plugin_Url_Colon {
            get {
                return ResourceManager.GetString("Plugin_Url_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running with Avalonia UI.
        /// </summary>
        public static string RunningWith {
            get {
                return ResourceManager.GetString("RunningWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autocomplete for function search.
        /// </summary>
        public static string Settings_AllowAutocompleteForFunctionSearch {
            get {
                return ResourceManager.GetString("Settings_AllowAutocompleteForFunctionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear function search if function was executed.
        /// </summary>
        public static string Settings_ClearSearchAfterFunctionExecute {
            get {
                return ResourceManager.GetString("Settings_ClearSearchAfterFunctionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close if a function was executed.
        /// </summary>
        public static string Settings_CloseOnFunctionExecute {
            get {
                return ResourceManager.GetString("Settings_CloseOnFunctionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep on Top.
        /// </summary>
        public static string Settings_KeepOnTop {
            get {
                return ResourceManager.GetString("Settings_KeepOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Taskbar.
        /// </summary>
        public static string Settings_ShowInTaskbar {
            get {
                return ResourceManager.GetString("Settings_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string Settings_WindowPosition_Bottom_Left {
            get {
                return ResourceManager.GetString("Settings_WindowPosition_Bottom_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string Settings_WindowPosition_Bottom_Right {
            get {
                return ResourceManager.GetString("Settings_WindowPosition_Bottom_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string Settings_WindowPosition_Top_Left {
            get {
                return ResourceManager.GetString("Settings_WindowPosition_Top_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string Settings_WindowPosition_Top_Right {
            get {
                return ResourceManager.GetString("Settings_WindowPosition_Top_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SubMenu_About {
            get {
                return ResourceManager.GetString("SubMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SubMenu_Exit {
            get {
                return ResourceManager.GetString("SubMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string SubMenu_Hide {
            get {
                return ResourceManager.GetString("SubMenu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SubMenu_Hotkeys {
            get {
                return ResourceManager.GetString("SubMenu_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SubMenu_Language {
            get {
                return ResourceManager.GetString("SubMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Function.
        /// </summary>
        public static string SubMenu_NewFunction {
            get {
                return ResourceManager.GetString("SubMenu_NewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string SubMenu_Plugins {
            get {
                return ResourceManager.GetString("SubMenu_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string SubMenu_ReportBug {
            get {
                return ResourceManager.GetString("SubMenu_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SubMenu_Settings {
            get {
                return ResourceManager.GetString("SubMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the application.
        /// </summary>
        public static string Tooltip_Hide {
            get {
                return ResourceManager.GetString("Tooltip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the application.
        /// </summary>
        public static string Tooltip_Show {
            get {
                return ResourceManager.GetString("Tooltip_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit function.
        /// </summary>
        public static string Window_EditFunction {
            get {
                return ResourceManager.GetString("Window_EditFunction", resourceCulture);
            }
        }
    }
}
