//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularToolManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModularToolManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to function.
        /// </summary>
        public static string AddFunction_FunctionPathWatermark {
            get {
                return ResourceManager.GetString("AddFunction_FunctionPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string AllPlugins_Header_Information {
            get {
                return ResourceManager.GetString("AllPlugins_Header_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AllPlugins_Header_Settings {
            get {
                return ResourceManager.GetString("AllPlugins_Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Tool Manager.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project website.
        /// </summary>
        public static string Button_Open_Project {
            get {
                return ResourceManager.GetString("Button_Open_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Default_Delete {
            get {
                return ResourceManager.GetString("Default_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Default_Edit {
            get {
                return ResourceManager.GetString("Default_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string DefaultButton_Abort {
            get {
                return ResourceManager.GetString("DefaultButton_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DefaultButton_Ok {
            get {
                return ResourceManager.GetString("DefaultButton_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string DefaultButton_OpenFile {
            get {
                return ResourceManager.GetString("DefaultButton_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DefaultButton_Save {
            get {
                return ResourceManager.GetString("DefaultButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for function.
        /// </summary>
        public static string FunctionSelection_SearchForFunction {
            get {
                return ResourceManager.GetString("FunctionSelection_SearchForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Description.
        /// </summary>
        public static string NewFunction_Description {
            get {
                return ResourceManager.GetString("NewFunction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Display Name.
        /// </summary>
        public static string NewFunction_Name {
            get {
                return ResourceManager.GetString("NewFunction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Parameters.
        /// </summary>
        public static string NewFunction_Parameters {
            get {
                return ResourceManager.GetString("NewFunction_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string Plugin_Authors_Colon {
            get {
                return ResourceManager.GetString("Plugin_Authors_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Plugin_Description_Colon {
            get {
                return ResourceManager.GetString("Plugin_Description_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Plugin_DisplayName_Colon {
            get {
                return ResourceManager.GetString("Plugin_DisplayName_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Plugin_License_Colon {
            get {
                return ResourceManager.GetString("Plugin_License_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project url:.
        /// </summary>
        public static string Plugin_Url_Colon {
            get {
                return ResourceManager.GetString("Plugin_Url_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep on Top.
        /// </summary>
        public static string Settings_KeepOnTop {
            get {
                return ResourceManager.GetString("Settings_KeepOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Taskbar.
        /// </summary>
        public static string Settings_ShowInTaskbar {
            get {
                return ResourceManager.GetString("Settings_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SubMenu_About {
            get {
                return ResourceManager.GetString("SubMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SubMenu_Exit {
            get {
                return ResourceManager.GetString("SubMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string SubMenu_Hide {
            get {
                return ResourceManager.GetString("SubMenu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SubMenu_Hotkeys {
            get {
                return ResourceManager.GetString("SubMenu_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SubMenu_Language {
            get {
                return ResourceManager.GetString("SubMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Function.
        /// </summary>
        public static string SubMenu_NewFunction {
            get {
                return ResourceManager.GetString("SubMenu_NewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string SubMenu_Plugins {
            get {
                return ResourceManager.GetString("SubMenu_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string SubMenu_ReportBug {
            get {
                return ResourceManager.GetString("SubMenu_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SubMenu_Settings {
            get {
                return ResourceManager.GetString("SubMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the application.
        /// </summary>
        public static string Tooltip_Hide {
            get {
                return ResourceManager.GetString("Tooltip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the application.
        /// </summary>
        public static string Tooltip_Show {
            get {
                return ResourceManager.GetString("Tooltip_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit function.
        /// </summary>
        public static string Window_EditFunction {
            get {
                return ResourceManager.GetString("Window_EditFunction", resourceCulture);
            }
        }
    }
}
