name: Check pull request

on: push
  #pull_request:
    #types: [closed]
    #branches: [ "develop" ]

env:
  DEBUG: true
  APPLICATION_PROJECT_PATH: .\src\ModularToolManager\ModularToolManager.csproj
  APPLICATION_PLUGIN_PROJECT_PATH: .\src\ModularToolManagerPlugin\ModularToolManagerPlugin.csproj
  APPLICATION_PUBLISH_FOLDER: ./publish
  PLUGIN_PUBLISH_FOLDER: ./publish/plugin
  WINDOWS_ARTIFACT_NAME: WindowsBuildArtifact

jobs:
  build:
    name: Create Windows build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Application
      run: dotnet publish $APPLICATION_PROJECT_PATH -r win-x64 -c Release -o $APPLICATION_PUBLISH_FOLDER
    - name: Publish Plugin
      run: dotnet publish $APPLICATION_PLUGIN_PROJECT_PATH -r win-x64 -c Release -o $PLUGIN_PUBLISH_FOLDER
    - name: Show content for debug
      if: ${{ env.DEBUG == true }}
      run: ls -la
    - name: Show content to publish
      if: ${{ env.DEBUG == true }}
      run: |
        cd ./publish
        ls -la
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
       name: $WINDOWS_ARTIFACT_NAME
       path: $APPLICATION_PUBLISH_FOLDER/
